### ISSUE TITLE
Windows defender found a trojan in ur mod (latest update)

### ISSUE THREAD

**Issue by MAYMAX** [risk-of-thunder/RoR2BepInExPack#25] opened 2024-05-30 15:08 UTC
![image](https://github.com/risk-of-thunder/RoR2BepInExPack/assets/88735681/7d32e6a3-b74f-4d5a-89e8-b53740b34437)

**Comment by harbingerofme** [comment] 2024-05-30 15:13
Which operating system are you on? Explicitly scanning the file on Windows 10.0.19045 does not produce reproduce this.

**Comment by xiaoxiao921** [comment] 2024-05-30 15:29
The file getting flagged is not that surprising, I'll try rewriting it with csharp only at some point but no promises. I guess we'll have to deal with such reports because the feature is too useful to pass on

**Comment by x753** [comment] 2024-05-31 00:00
A friend of mine got this as well and it quarantined the file.

**Comment by vSusGamertag** [comment] 2024-05-31 00:28
Windows defender quarantined the file for me also. Friends not using windows defender did not have any issues.

**Comment by MAYMAX** [comment] 2024-05-31 07:05
> Which operating system are you on? Explicitly scanning the file on Windows 10.0.19045 does not produce reproduce this.

i'm using win 10 19045,4412
i scanned the whole folder and it showed up as a trojan again

**Comment by NyxBornee** [comment] 2024-05-31 07:30
Same issue here using a developer version of windows 11

**Comment by Anhrak** [comment] 2024-05-31 09:29
Came here with the same issue, windows defender flags/reports the new frankenmonoprintstackoverflowexception.dll file as part of the 1.12 update as a Trojan.

**Comment by Nyther** [comment] 2024-05-31 20:13
Same issue on my Win 10, Windows Defender flagged 2 files as Trojans, tried to restore them and run the game through r2modman and it my PC crashed, jsut straight up reseted.

**Comment by xArkailzx** [comment] 2024-06-01 09:07
Same issue on Win 11 last version:
![image](https://github.com/risk-of-thunder/RoR2BepInExPack/assets/78084119/a07539e4-9bfd-49f1-a0c2-c5958df35f84)

It probably has something to do with this:
![image](https://github.com/risk-of-thunder/RoR2BepInExPack/assets/78084119/1fc29e11-949b-493a-a1e9-dc2cf9b4eca5)

Also:
> The file getting flagged is not that surprising, I'll try rewriting it with csharp only at some point but no promises. I guess we'll have to deal with such reports because the feature is too useful to pass on

I don't want to be alarmist, but... false positives are pretty rare nowadays, especially on Win 11.

**Comment by xiaoxiao921** [comment] 2024-06-01 09:23
Fixed by https://github.com/risk-of-thunder/RoR2BepInExPack/commit/cf3d69d93179d6e36b801783cdff29c99a5f4edc

**Closed as completed by xiaoxiao921** 2024-06-01 09:23 UTC
